server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.example.gateway.filter: DEBUG
    reactor.netty.http.server: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE


spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: casesecretkey123456789012345678901234

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/user/**

        - id: hotel-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/hotels/**, /api/hotels, /api/rooms/**, /api/rooms
            - Method=GET,POST,PUT,DELETE

        - id: reservation-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/reservations/**, /api/reservations
            - Method=GET,POST,PUT,DELETE

        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/notifications/**
            - Method=GET,POST,PUT,DELETE

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS

jwt:
  secret: casesecretkey123456789012345678901234