server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
#    com.example.gateway.filter: DEBUG
#    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE


spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: casesecretkey123456789012345678901234

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8084
          predicates:
            - Path=/api/user/**

        - id: hotel-service
          uri: http://hotel-service:8081
          predicates:
            - Path=/api/hotels/**, /api/rooms/**

        - id: reservation-service
          uri: http://reservation-service:8083
          predicates:
            - Path=/api/reservations/**

        - id: notification-service
          uri: http://notification-service:8082
          predicates:
            - Path=/api/notifications/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS

jwt:
  secret: casesecretkey123456789012345678901234