version: '3.8'
services:
  postgres-db:
    image: postgres:17
    container_name: user_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotel_user
    ports:
      - "5435:5432"

  user-service:
    container_name: user_service
    build: .
    ports:
      - "8084:8084"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/hotel_user
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres